// Mocks generated by Mockito 5.4.6 from annotations
// in grocery/test/features/compliance/printer_and_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i4;

import 'package:blue_thermal_printer/blue_thermal_printer.dart' as _i2;
import 'package:grocery/core/services/supabase_storage_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BlueThermalPrinter].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlueThermalPrinter extends _i1.Mock
    implements _i2.BlueThermalPrinter {
  MockBlueThermalPrinter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool?> get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> get isOn => (super.noSuchMethod(
        Invocation.getter(#isOn),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> get openSettings => (super.noSuchMethod(
        Invocation.getter(#openSettings),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Stream<int?> onStateChanged() => (super.noSuchMethod(
        Invocation.method(
          #onStateChanged,
          [],
        ),
        returnValue: _i3.Stream<int?>.empty(),
      ) as _i3.Stream<int?>);

  @override
  _i3.Stream<String> onRead() => (super.noSuchMethod(
        Invocation.method(
          #onRead,
          [],
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<List<_i2.BluetoothDevice>> getBondedDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBondedDevices,
          [],
        ),
        returnValue: _i3.Future<List<_i2.BluetoothDevice>>.value(
            <_i2.BluetoothDevice>[]),
      ) as _i3.Future<List<_i2.BluetoothDevice>>);

  @override
  _i3.Future<bool?> isDeviceConnected(_i2.BluetoothDevice? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDeviceConnected,
          [device],
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<dynamic> connect(_i2.BluetoothDevice? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [device],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> write(String? message) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [message],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> writeBytes(_i4.Uint8List? message) => (super.noSuchMethod(
        Invocation.method(
          #writeBytes,
          [message],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> printCustom(
    String? message,
    int? size,
    int? align, {
    String? charset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printCustom,
          [
            message,
            size,
            align,
          ],
          {#charset: charset},
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> printNewLine() => (super.noSuchMethod(
        Invocation.method(
          #printNewLine,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> paperCut() => (super.noSuchMethod(
        Invocation.method(
          #paperCut,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> drawerPin2() => (super.noSuchMethod(
        Invocation.method(
          #drawerPin2,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> drawerPin5() => (super.noSuchMethod(
        Invocation.method(
          #drawerPin5,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> printImage(String? pathImage) => (super.noSuchMethod(
        Invocation.method(
          #printImage,
          [pathImage],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> printImageBytes(_i4.Uint8List? bytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #printImageBytes,
          [bytes],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> printQRcode(
    String? textToQR,
    int? width,
    int? height,
    int? align,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #printQRcode,
          [
            textToQR,
            width,
            height,
            align,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> printLeftRight(
    String? string1,
    String? string2,
    int? size, {
    String? charset,
    String? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printLeftRight,
          [
            string1,
            string2,
            size,
          ],
          {
            #charset: charset,
            #format: format,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> print3Column(
    String? string1,
    String? string2,
    String? string3,
    int? size, {
    String? charset,
    String? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #print3Column,
          [
            string1,
            string2,
            string3,
            size,
          ],
          {
            #charset: charset,
            #format: format,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> print4Column(
    String? string1,
    String? string2,
    String? string3,
    String? string4,
    int? size, {
    String? charset,
    String? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #print4Column,
          [
            string1,
            string2,
            string3,
            string4,
            size,
          ],
          {
            #charset: charset,
            #format: format,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}

/// A class which mocks [SupabaseStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseStorageService extends _i1.Mock
    implements _i5.SupabaseStorageService {
  MockSupabaseStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> uploadProductImage({
    required _i6.File? imageFile,
    required String? tenantId,
    required String? productId,
    void Function(
      int,
      int,
    )? onUploadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProductImage,
          [],
          {
            #imageFile: imageFile,
            #tenantId: tenantId,
            #productId: productId,
            #onUploadProgress: onUploadProgress,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
