name: grocery
description: "A Multi-Tenant, Offline-First Grocery POS for Myanmar."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Backend & Auth
  supabase_flutter: ^2.12.0
  
  # Environment Variables
  flutter_dotenv: ^6.0.0
  
  # Utilities
  geolocator: ^11.0.0
  network_info_plus: ^5.0.1
  drift: ^2.31.0
  sqlcipher_flutter_libs: ^0.6.8
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.2
  intl: ^0.20.2
  blue_thermal_printer: ^1.2.3
  screenshot: ^3.0.0
  image: ^4.7.2
  image_picker: ^1.0.7
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.2.4
  infinite_scroll_pagination: ^5.1.1
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0


  crypto: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.11.1
  drift_dev: ^2.32.1
  mockito: ^5.4.4

  matcher: any
dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.17
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true

  # Register .env so the app can load keys
  assets:
    - .env.example

  # Myanmar Font Support
  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-Regular.ttf
        - asset: assets/fonts/Pyidaungsu-Bold.ttf
          weight: 700
